Controllers/UserLoginController.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using FinalProject.Repository;
using BCrypt.Net;
using FinalProject.Common;


namespace FinalProject.Controllers
{
    public class UserLoginController : Controller
    {
        ///GET: Login <summary>
        /// GET: Login
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// GET: Login
        /// </summary>
        /// <param name="login"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Index(LoginClass login)
        {
            try
            {
                string mainconn = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;
                SqlConnection sqlconn = new SqlConnection(mainconn);
                
                // Check if the user is an admin
                if (login.EmailAddress == "admin1@gmail.com" && login.Password == "Admin@123")
                {
                    // Admin login
                    FormsAuthentication.SetAuthCookie(login.EmailAddress, true);
                    Session["emailid"] = login.EmailAddress.ToString();
                    return RedirectToAction("AdminHome", "Admin");
                }
                else
                {
                    // Regular user login
                    SqlCommand sqlcomm = new SqlCommand("SPS_FinalLogin", sqlconn);
                    sqlcomm.CommandType = CommandType.StoredProcedure;
                    sqlcomm.Parameters.AddWithValue("@EmailAddress", login.EmailAddress);
                    sqlcomm.Parameters.AddWithValue("@Password", Password.Encode(login.Password));

                    sqlconn.Open();
                    SqlDataReader sqr = sqlcomm.ExecuteReader();
                    
                    if (sqr.Read())
                    {
                        FormsAuthentication.SetAuthCookie(login.EmailAddress, true);
                        Session["emailid"] = login.EmailAddress.ToString();
                        return RedirectToAction("UserHome", "UserLogin");

                    }
                    else
                    {
                        ViewData["message"] = "Username & Password are wrong!";
                    }

                    sqlconn.Close();
                }
            }
            catch(Exception ex)
            {
                ViewData["message"] = "An error occurred: " + ex.Message;
                LogError(logFilePath, ex);
            }
            return View();
        }
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Welcome()
        {
          try
            {
            string loggedInEmail = (string)Session["emailid"];
            string connectionString = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                SqlCommand command = new SqlCommand("SPS_GetUserDetails", connection);
                command.CommandType = CommandType.StoredProcedure;
                command.Parameters.AddWithValue("@EmailAddress", loggedInEmail);

                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                UserClass user = new UserClass();
                    Response.Cache.SetCacheability(HttpCacheability.NoCache);
                    Response.Cache.SetNoStore();
                    if (reader.Read())
                    {
                    string image = reader["Photo"].ToString();
                    ViewData["Img"] = image;
                    TempData["Oldimg"] = image;

                    user.FirstName = reader["FirstName"].ToString();
                    user.LastName = reader["LastName"].ToString();
                    user.DateOfBirth = (DateTime)reader["DateOfBirth"];
                    user.Gender = reader["Gender"].ToString();
                    user.PhoneNumber = reader["PhoneNumber"].ToString();
                    user.EmailAddress = reader["EmailAddress"].ToString();
                    user.Address = reader["Address"].ToString();
                    user.Country = reader["Country"].ToString();
                    user.State = reader["State"].ToString();
                    user.City = reader["City"].ToString();
                    user.Postcode = reader["Postcode"].ToString();
                    user.PassportNumber = reader["PassportNumber"].ToString();
                    user.Username = reader["Username"].ToString();
                    user.Password = reader["Password"].ToString();
                    }

                connection.Close();
                return View(user);
            }
        }
            catch (Exception ex)
            {
                // Handle exception or log error
                ViewData["message"] = "An error occurred: " + ex.Message;
                LogError(logFilePath, ex);
            }

            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="file"></param>
        /// <returns></returns>
        public ActionResult UserImageChange(HttpPostedFileBase file)
        {
            try
            {
                var emailId = (string)Session["emailid"];

                string imgpath = Server.MapPath((string)TempData["Oldimg"]);
                string fileimgpath = imgpath;
                FileInfo fileInfo = new FileInfo(fileimgpath);
                
                if (fileInfo.Exists)
                {
                    fileInfo.Delete();
                }

                if (file != null && file.ContentLength > 0)
                {
                    string filename = Path.GetFileName(file.FileName);
                    string filepath = Path.Combine(Server.MapPath("/User-Images/"), filename);
                    file.SaveAs(filepath);

                    string mainconn = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;
                    using (SqlConnection sqlconn = new SqlConnection(mainconn))
                    {
                        sqlconn.Open();
                        SqlCommand sqlcomm = new SqlCommand("SPU_UpdateUserPhoto", sqlconn);
                        sqlcomm.CommandType = CommandType.StoredProcedure;
                        sqlcomm.Parameters.AddWithValue("@Photo", "/User-Images/" + filename);
                        sqlcomm.Parameters.AddWithValue("@EmailAddress", emailId);
                        sqlcomm.ExecuteNonQuery();
                    }
                }
            }
            catch (Exception ex)
            {
                // Handle exception or log error
                ViewData["message"] = "An error occurred: " + ex.Message;
                LogError(logFilePath, ex);
            }
            return RedirectToAction("Welcome", "UserLogin");
        }


        /// <summary>
        /// POST: Login/UpdateUser
        /// </summary>
        /// <param name="user"></param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("UpdateUser")]
        public ActionResult UpdateUser(UserClass user)
        {
            try
            {
                string mainconn = ConfigurationManager.ConnectionStrings["Myconnection"].ConnectionString;
                using (SqlConnection sqlconn = new SqlConnection(mainconn))

                {
                    sqlconn.Open();
                    SqlCommand sqlcommand = new SqlCommand("SPU_UpdateUser", sqlconn);
                    sqlcommand.CommandType = CommandType.StoredProcedure;
                   

                    sqlcommand.Parameters.AddWithValue("@FirstName", user.FirstName);
                    sqlcommand.Parameters.AddWithValue("@LastName", user.LastName);
                    sqlcommand.Parameters.AddWithValue("@DateOfBirth", user.DateOfBirth);
                    sqlcommand.Parameters.AddWithValue("@Gender", user.Gender);
                    sqlcommand.Parameters.AddWithValue("@PhoneNumber", user.PhoneNumber);
                    sqlcommand.Parameters.AddWithValue("@Address", user.Address);
                    sqlcommand.Parameters.AddWithValue("@Country", user.Country);
                    sqlcommand.Parameters.AddWithValue("@State", user.State);
                    sqlcommand.Parameters.AddWithValue("@City", user.City);
                    sqlcommand.Parameters.AddWithValue("@Postcode", user.Postcode);
                    sqlcommand.Parameters.AddWithValue("@PassportNumber", user.PassportNumber);
                    sqlcommand.Parameters.AddWithValue("@Username", user.Username);                 
                    sqlcommand.Parameters.AddWithValue("@EmailAddress", user.EmailAddress);
                    sqlcommand.ExecuteNonQuery();
                }
            }
            catch (Exception ex)
            {
                // Handle exception or log error
                ViewData["message"] = "An error occurred: " + ex.Message;
                LogError(logFilePath, ex);
            }
            return RedirectToAction("Welcome");
        }

        public ActionResult ChangePassword()
        {
            ViewBag.Message = "Change Password page";

            return View();
        }

        [HttpPost]
       [ValidateAntiForgeryToken]
        public ActionResult ChangePassword(ChangePasswordModel model)
        {
         try
        {

Controllers/UserRegistrationController.cs
using FinalProject.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FinalProject.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;
using System.Web.UI;
using FinalProject.Repository;
using FinalProject.Common;

namespace FinalProject.Controllers
{
    public class UserRegistrationController : Controller
    {
        // GET: NewReg
        public ActionResult Index()
        {
            return View();
        }



        // Post: NewReg
        [HttpPost]
        public ActionResult Index(UserClass userClass, HttpPostedFileBase file)
        {
            try
            {
            string mainconn = ConfigurationManager.ConnectionStrings["MyConnection"].ConnectionString;
            SqlConnection sqlconn = new SqlConnection(mainconn);
            string encodedPassword = Password.Encode(userClass.Password);


            SqlCommand sqlCommand = new SqlCommand("SPI_InsertUserReg", sqlconn);
            sqlCommand.CommandType = CommandType.StoredProcedure;

            sqlCommand.Parameters.AddWithValue("@FirstName", userClass.FirstName);
            sqlCommand.Parameters.AddWithValue("@LastName", userClass.LastName);
            sqlCommand.Parameters.AddWithValue("@DateOfBirth", userClass.DateOfBirth);
            sqlCommand.Parameters.AddWithValue("@Gender", userClass.Gender);
            sqlCommand.Parameters.AddWithValue("@PhoneNumber", userClass.PhoneNumber);
            sqlCommand.Parameters.AddWithValue("@EmailAddress", userClass.EmailAddress);
            sqlCommand.Parameters.AddWithValue("@Address", userClass.Address);
            sqlCommand.Parameters.AddWithValue("@Country", userClass.Country);
            sqlCommand.Parameters.AddWithValue("@State", userClass.State);
            sqlCommand.Parameters.AddWithValue("@City", userClass.City);
            sqlCommand.Parameters.AddWithValue("@Postcode", userClass.Postcode);
            sqlCommand.Parameters.AddWithValue("@PassportNumber", userClass.PassportNumber);
            sqlCommand.Parameters.AddWithValue("@Username", userClass.Username);
            sqlCommand.Parameters.AddWithValue("@Password", encodedPassword);

                
                if (file != null && file.ContentLength > 0)
            {

                string filename = Path.GetFileName(file.FileName);
                string imgpath = Path.Combine(Server.MapPath("/User-Images/"), filename);
                file.SaveAs(imgpath);
                sqlCommand.Parameters.AddWithValue("@Photo", "/User-Images/" + filename);
            }
            else
            {
                sqlCommand.Parameters.AddWithValue("@Photo", DBNull.Value);
            }
            sqlconn.Open();
            sqlCommand.ExecuteNonQuery();
            sqlconn.Close();

            ViewData["Message"] = "User Record " + userClass.FirstName + " Is Saved Successfully!";
            return View();
            }
            catch (Exception ex)
            {
                ViewData["ErrorMessage"] = "An error occurred while saving the user record: " + ex.Message;
                LogError(logFilePath, ex);
                return View();
            }

        }


        /// <summary>
        /// ErrorLog file
        /// </summary>
        string logFilePath = "C:\\Users\\IJAS\\source\\repos\\FinalProject\\ErrorLog.txt";
        private void LogError(string logFilePath, Exception ex)
        {
            using (StreamWriter writer = new StreamWriter(logFilePath, true))
            {
                writer.WriteLine("Error Date: " + DateTime.Now.ToString());
                writer.WriteLine("Message:" + ex.Message);
                writer.WriteLine("Stack Trace:" + ex.StackTrace);
                writer.WriteLine("-----------------------------------------------");

            }
        }


    }
}

Views/UserLogin/ChangePassword.cshtml
@model FinalProject.Models.ChangePasswordModel

@{
    ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_LayoutPageUser.cshtml";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ChangePassword</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"></script>
</head>
<body>

    <h2>Change password</h2>


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.OldPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.OldPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.OldPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.NewPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NewPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NewPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }



    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript">
            function preventBack() {
                window.history.forward();
            }
            setTimeout("preventBack()", 0);
            window.onunload = function () { null };
        </script>
    }
</body>
</html>

Views/UserLogin/CheckStatus.cshtml
@model FinalProject.Models.VisaStatus

@{
    ViewBag.Title = "CheckStatus";
    Layout = "~/Views/Shared/_LayoutPageUser.cshtml";
}


<link href="~/Content/CSS/CheckStatus.css" rel="stylesheet" />

<h2>CheckStatus</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmailID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PassportNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PassportNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PassportNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript">
    function preventBack() {
    window.history.forward();
    }
    setTimeout("preventBack()", 0);
    window.onunload = function () { null };
</script>
}

Views/UserLogin/Index.cshtml
@model FinalProject.Models.LoginClass

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@if (!string.IsNullOrEmpty(ViewData["message"] as string))
{
    <div class="alert alert-danger" role="alert">
        @ViewData["message"]
    </div>
}

<!DOCTYPE html>
<html>
<head>
    <title>User Signin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"></script>
    <link href="~/Content/CSS/Signin.css" rel="stylesheet" />

</head>
<body>


    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col col-xl-10">
                    <div class="card" style="border-radius: 1rem;">
                        <div class="row g-0">
                            <div class="col-md-6 col-lg-5 d-none d-md-block">
                                <img src="https://images.pexels.com/photos/7235902/pexels-photo-7235902.jpeg?auto=compress&cs=tinysrgb&w=600"
                                     alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                            </div>
                            <div class="col-md-6 col-lg-7 d-flex align-items-center">
                                <div class="card-body p-4 p-lg-5 text-black">
                                    <div class="d-flex align-items-center mb-3 pb-1">

                                        <span class="h1 fw-bold mb-0">Sign in</span>
                                    </div>
                                    @using (Html.BeginForm())
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="form-outline mb-4">
                                            @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control form-control-lg", @onfocusout = "validateEmailAddress()" } })
                                            @Html.LabelFor(model => model.EmailAddress, new { @class = "form-label" })
                                            @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
                                            <span id="emailAddressError" class="text-danger"></span>
                                        </div>
                                        <div class="form-outline mb-4">
                                            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control form-control-lg", @onfocusout = "validatePassword()" } })
                                            @Html.LabelFor(model => model.Password, new { @class = "form-label" })
                                            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                            <span id="passwordErrorMessage" class="text-danger"></span>
                                        </div>
                                        <div class="pt-1 mb-4">
                                            <input type="submit" value="Login" class="btn btn-dark btn-lg btn-block" />
                                        </div>
                                        <p class="mb-5 pb-lg-2" style="color: #393f81;">
                                            Don't have an account? <a href=""
                                                                      style="color: #393f81;">@Html.ActionLink("Register here", "Index", "UserRegistration")</a>
                                                                </p>
                                                            }
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <div class="footercolor">

        <!-- Footer -->
        <footer class=" text-center text-dark">
            <!-- Grid container -->
            <div class="container p-4 footerayshel">
                <!-- Section: Social media -->
                <section class="mb-4">
                    <!-- Facebook -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="#!" role="button">
                        <i class="fab fa-facebook"></i>
                    </a>


                    <!-- Google -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="https://www.justdial.com/Malappuram/Ayshel-Boutique-Near-Musjid-Mangalam-Mlp/9999PX483-X483-190322202629-T6N6_BZDET" role="button">
                        <i class="fab fa-google"></i>
                    </a>

                    <!-- Instagram -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="https://www.instagram.com/ayshellshop/?hl=en" role="button">
                        <i class="fab fa-instagram"></i>
                    </a>

                    <!-- Linkedin -->
                    <a class="btn btn-outline-dark btn-floating m-1" href="#!" role="button">
                        <i class="fab fa-linkedin-in"></i>
                    </a>


                    <!-- Section: Social media -->
                    <!-- Section: Text -->
                    <section class="mb-4">
                        <p>
                            Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals.
                        </p>
                    </section>
                    <!-- Section: Text -->
                    <!-- Copyright -->

        </footer>



        <div class="footerayshel">
            <div class="text-center p-3 " style="background-color: rgba(0, 0, 0, 0.2);">
                © 2020 Copyright:
                <a class="text-dark" href="https://mdbootstrap.com/">E-Visa.com</a>
            </div>
        </div>

    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script type="text/javascript">
            function preventBack() {
                window.history.forward();
            }
            setTimeout("preventBack()", 0);
            window.onunload = function () { null };


            function validateEmailAddress() {
                var emailAddressInput = document.getElementById('EmailAddress');
                var emailAddressErrorMessage = document.getElementById('emailAddressError');

                if (emailAddressInput.value.trim() === '') {
                    emailAddressErrorMessage.textContent = 'Email address is required.';
                } else {
                    emailAddressErrorMessage.textContent = '';
                }
            }

            function validatePassword() {
                var passwordInput = document.getElementById('Password');
                var passwordErrorMessage = document.getElementById('passwordError');

                if (passwordInput.value.trim() === '') {
                    passwordErrorMessage.textContent = 'Password is required.';
                } else {
                    passwordErrorMessage.textContent = '';
                }
            }
        </script>
    }
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/UserLogin/Welcome.cshtml

@{
    ViewBag.Title = "UserWelcome";
    Layout = "~/Views/Shared/_LayoutPageUser.cshtml";
}




<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">


                    @if (Session["emailid"] != null)
                    {
                        <h2 class="text-center">welcome @Session["emailid"].ToString()</h2>
                        <div class="text-center">
                            <img src="@Html.ViewData["Img"]" alt="image" height="150" width="150" />




                            <h3>User Details:</h3>
                            <table style="margin: 0 auto;">
                                <tr>
                                    <th>First Name:</th>
                                    <td>@Model.FirstName</td>
                                </tr>
                                <tr>
                                    <th>Last Name:</th>
                                    <td>@Model.LastName</td>
                                </tr>
                                <tr>
                                    <th>Date of Birth:</th>
                                    <td>@Model.DateOfBirth.ToShortDateString()</td>
                                </tr>
                                <tr>
                                    <th>Gender:</th>
                                    <td>@Model.Gender</td>
                                </tr>
                                <tr>
                                    <th>Phone Number:</th>
                                    <td>@Model.PhoneNumber</td>
                                </tr>
                                <tr>
                                    <th>Email Address:</th>
                                    <td>@Model.EmailAddress</td>
                                </tr>
                                <tr>
                                    <th>Country:</th>
                                    <td>@Model.Country</td>
                                </tr>
                                <tr>
                                    <th>State:</th>
                                    <td>@Model.State</td>
                                </tr>
                                <tr>
                                    <th>City:</th>
                                    <td>@Model.City</td>
                                </tr>
                                <tr>
                                    <th>Postcode:</th>
                                    <td>@Model.Postcode</td>
                                </tr>
                                <tr>
                                    <th>PassportNumber:</th>
                                    <td>@Model.PassportNumber</td>
                                </tr>

                                <tr>
                                    <th>Username:</th>
                                    <td>@Model.Username</td>
                                </tr>
                                <tr>
                                    <th>Password:</th>
                                    <td>@Model.Password</td>
                                </tr>
                            </table>

                        </div>

                    }
                    <div class="text-center">
                        @using (Html.BeginForm("UpdateUser", "UserLogin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()

                            <div>
                                @Html.ActionLink("Update Profile", "UpdateUser", "UserLogin", null, new { })
                            </div>
                        }

                        <h3>Update Profile Image</h3>
                        <hr />
                        @using (Html.BeginForm("UserImageChange", "UserLogin", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="d-flex align-items-center text-center">
                                <input type="file" name="file" />
                                <br />
                                <input type="submit" value="Update Image" />
                            </div>
                        }



                    </div>



                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
            function preventBack() {
                window.history.forward();
            }
            setTimeout("preventBack()", 0);
    window.onunload = function () { null };
            </script>